# Generated by Django 5.0.6 on 2024-06-09 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_categoria', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, max_length=250)),
                ('tipo', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('aceite_termo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Debito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_debito', models.CharField(max_length=50)),
                ('data_saida', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, max_length=250)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_credito', models.CharField(max_length=50)),
                ('data_entrada', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, max_length=250)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.usuario')),
            ],
        ),
    ]
