# Generated by Django 5.0.3 on 2024-05-15 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icone',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='credito',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.categoria'),
        ),
    ]
