# Generated by Django 5.0.3 on 2024-05-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_remove_categoria_icone_categoria_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='credito',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas.categoria'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='descricao',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='credito',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='debito',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas.categoria'),
        ),
        migrations.AlterField(
            model_name='debito',
            name='descricao',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='debito',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
